# Execute the "bosh status --uuid" command to obtain the director_uuid.
director_uuid: yyy

meta:
  db:
      user: db_user
      pass: db_pass
      host: db_host
  properties:
    nats:
        password: NATS_PASSWORD
    redis:
      password: REDIS_PASS
    dns:
      user: POWERDNS_USER
      password: POWERDNS_PASSWORD
      webserver: {password: WEB_PASSWORD}
      replication:
        basic_auth: REPUSER:ENCRPTED_PASS
        user: REPUSER
        password: REP_PASS
    registry:
      http:
        user: HTTP_USER
        password: HTTP_PASSWORD
      username: REGISTRY_USER
      password: REGISTRY_PASS
    blobstore:
      director:
        password: BLOB_DIRECTOR_PASS
      agent:
        password: BLOB_AGENT_PASS
    director:
      admin_pass: DIRECTOR_ADMIN_PASS
      hm_pass: DIRECTOR_HM_PASS
  aws:
    access_key_id: AWS_ACCESS_KEY
    secret_access_key: AWS_SECRET_KEY
    default_key_name: datagov_bosh
    default_security_groups: [datagov_bosh]
    region: us-east-1




jobs:
- name: bosh
  properties:
    aws: &aws
      access_key_id: AWS_ACCESS_KEY
      secret_access_key: AWS_SECRET_KEY
      default_key_name: datagov_bosh
      default_security_groups: [datagov_bosh]
      region: us-east-1
    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]


cloud_provider:
  ssh_tunnel:
    host: 52.1.221.149
    private_key: ./datagov_bosh.pem # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@((meta.networks.bosh.static_ips)):6868"
