name: datagov-dockerswarm
director_uuid: DIRECTOR_UUID # run $(bosh status --uuid)

meta:
  networks:
    dns: [BOSH_DIRECOR_INTERNALIP, AWS_DNS]
    range: IP_RANGE
    gateway: AWS_SUBNET_GATEWAY
    reserved: [FIRST4_OF_AWS_SUBNET]
    static: [AVAILABLE_STATIC]
    subnet_id: AWS_SUBNET_ID
    security_groups:
      - AWS_SECURITYGROUP_NAME
      - SECOND_SG_NAME
    controller_ip: STATIC_IP_FOR_SHIPYARD_CONTROLLER
    elbs: [AWS_ELB]


